const cmsForm = {
  id: 1,
  title: "Contact Form",
  fields: [
    {
      id: "68313474bb5d9284426532ca",
      name: "Name",
      label: "Name",
      width: null,
      defaultValue: null,
      required: true,
      blockName: null,
      blockType: "text",
    },
    {
      id: "6831349cbb5d9284426532cc",
      name: "Phone",
      label: "Phone",
      width: null,
      defaultValue: null,
      required: true,
      blockName: null,
      blockType: "text",
    },
    {
      id: "683134b0bb5d9284426532ce",
      name: "Company",
      label: "Company",
      width: null,
      defaultValue: null,
      required: true,
      blockName: null,
      blockType: "text",
    },
    {
      id: "683134d5bb5d9284426532d0",
      name: "Email",
      label: "Email",
      width: null,
      required: true,
      blockName: null,
      blockType: "email",
    },
  ],
  submitButtonLabel: "Send",
  confirmationType: "message",
  confirmationMessage: {
    root: {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "Form submitted",
              type: "text",
              version: 1,
            },
          ],
          direction: "ltr",
          format: "",
          indent: 0,
          type: "paragraph",
          version: 1,
          textFormat: 0,
          textStyle: "",
        },
      ],
      direction: "ltr",
      format: "",
      indent: 0,
      type: "root",
      version: 1,
    },
  },
  redirect: {
    url: "localhost.com",
  },
  updatedAt: "2025-05-24T03:06:44.123Z",
  createdAt: "2025-05-24T02:55:16.379Z",
  emails: [],
};

export default cmsForm;
